BTY-0017: Categories + BTY-0020: Price Schedule
nataliiaAndrosova/bty-admin-fe pull request #11
Opened 2021-11-05 20:28 UTC by mlnkbohdan

2021-11-25 10:56 UTC, nataliiaAndrosova requested changes

2021-11-25 11:28 UTC, mlnkbohdan commented on src/components/ProductForm.tsx
> +  const { priceSchedules } = usePriceSchedules().data
price schedules fetching moved up in AddProduct and EditProduct. the productForm gets an empty array if request has failed.

2021-11-25 11:28 UTC, mlnkbohdan commented on src/hooks/usePriceSchedule.ts
> +export function usePriceSchedule (id: string): QueryResult<PriceSchedule, {message: string}> { // this hook has not been used
steel not used

2021-11-25 11:28 UTC, mlnkbohdan commented on src/components/CategoryForm.tsx
> +      console.log(payload)
fixed

2021-11-25 11:28 UTC, mlnkbohdan commented on src/components/CategoryForm.tsx
> +      alert('Type category name')
fixed (used bootstrap alert component)

2021-11-26 22:25 UTC, nataliiaAndrosova requested changes

2021-11-26 22:25 UTC, nataliiaAndrosova commented on src/components/ProductForm.tsx
> +    if (values.price === null) {
should be initialValues.price === null ???

2021-11-26 22:25 UTC, nataliiaAndrosova commented on src/components/PriceScheduleForm.tsx
> +  const [config, setConfig] = useState(initialValues.configuration)
it might make sense to split this component into two 'PriceScheduleForm' & 'ScheduleList'

2021-11-26 22:25 UTC, nataliiaAndrosova commented on src/components/ProductForm.tsx
> +    if (payload.priceSchedule === '') {
modification of payload should "live" in hook

2021-11-26 22:25 UTC, nataliiaAndrosova commented on src/screens/Products/Product/AddProduct.tsx
> +      <CategoriesMenu
CategoriesMenu is not related to Categories screen. It should be implemented as a separate component in components library and used then in ProductForm

2021-11-26 22:25 UTC, nataliiaAndrosova commented on src/screens/categories/category/AddCategory.tsx
> +      <CategoryForm onSubmit={handleSubmit} queryInfo={createCategoryInfo} submitText={'Create category'}/>
error handling is missing

2021-11-26 22:25 UTC, nataliiaAndrosova commented on src/screens/categories/category/EditCategory.tsx
> +      <CategoryForm
error handling is missing

2021-11-26 22:25 UTC, nataliiaAndrosova commented on src/screens/priceSchedule/index.tsx
> +  const { priceSchedules } = usePriceSchedules().data
what is server responds with 500 (Internal server error) here?

2021-12-05 12:52 UTC, merged